services:

 minio-client:
  image: minio/mc:latest
  restart: always
  network_mode: host
  volumes:
    - ./resources:/resources:ro
  entrypoint: >
    /bin/sh -c "
    /usr/bin/mc alias set minio http://localhost:9000 flux toolkit.fluxcd.io --api S3v4;
    /usr/bin/mc mirror --watch /resources/ minio/flux 
    "