# Creates a kind cluster with a registry.
---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5000

---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: flux-helm
  nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker