apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 3m
  install:
    createNamespace: true
  targetNamespace: pod-info
  values:
    replicaCount: 2